### ISSUE TITLE
Testing github feature

### ISSUE THREAD

**Issue by stevenhwu** [stevenhwu/stevenhwu.github.io#13]
@kentdan Can you try something with your forked repo for me?
Can you try to change your repo [stevenhwu.github.io](https://github.com/kentdan/stevenhwu.github.io) to private?
I assume even me (original owner of the repo) can't see that.

Cheers
Steven

**Comment by kentdan** [comment]
Hi Steven,
I can't change the visibility of the forked repo in GitHub. p.s How to send
messages directly from Github?
Currently, I am sending the message using my email

Cheers
Kent

**Comment by stevenhwu** [comment]
i.e. reply directly using email lol. Or try the comment box in the issue.
[image: image.png]

**Comment by stevenhwu** [comment]
```R
test <- function(x){
  x + 1
  }
```

```python
test <- function(x){
  x + 1
  }
```

# Alumni
## Stu Dent 2
### heading 3
#### heading 4
- aoeu
  - aoeu 2
    - aoeu 3
  1. **subtaks** 1
      10. add new task
  2. aoeu
  3. aoeu 
- aoeu
1. task 1
2. taks 2

- aoeu

1. 

- **_## Past member_**
